### ISSUE TITLE
undefined reference to `_strnicmp'

### ISSUE THREAD

**Issue by Remi-Coulom** [accreator/Yixin-Board#9]
I tried to compile in Ubuntu 14.04.5 LTS, and it failed with this error:
```
/tmp/ccPLZCjN.o: In function `execute_command':
main.c:(.text+0x9b90): undefined reference to `_strnicmp'
main.c:(.text+0x9be0): undefined reference to `_strnicmp'
main.c:(.text+0x9c09): undefined reference to `_strnicmp'
main.c:(.text+0xa111): undefined reference to `_strnicmp'
main.c:(.text+0xa12d): undefined reference to `_strnicmp'
/tmp/ccPLZCjN.o:main.c:(.text+0xa1f7): more undefined references to `_strnicmp' follow
collect2: error: ld returned 1 exit status

```

**Comment by accreator** [comment]
_strnicmp is only available in msvc. For other compilers, You may try redefining _strnicmp to strnicmp.

**Comment by Remi-Coulom** [comment]
In fact, strnicmp is not available either.  it is strncasecmp.
